version: '3.4'

services:
  assetsdb:
    container_name: assetsdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  schedulerdb:
    container_name: schedulerdb
    restart: always
    ports:
      - "6379:6379"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8090:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  assets.api:
    container_name: assets.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://assetsdb:27017"
    depends_on:
      - assetsdb
    ports:
      - "8050:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  scheduler.api:
    container_name: scheduler.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=schedulerdb:6379"
    depends_on:
      - schedulerdb
    ports:
      - "8051:80"

