version: '3.4'

services:
  assetsdb:
    container_name: assetsdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  assets.api:
    container_name: assets.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://assetsdb:27017"
    depends_on:
      - assetsdb
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro